name: SimpleStats
description: Stats Plugin made by GamilinoMC
author: GamilinoMC
api:
  - 5.0.0
main: ZebraMC\GamilinoMC\Stats
version: 1.0.0

permissions:
  stats.cmd:
    default: true
    description: Stats Command
